name: materi_kas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2719.3
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  csv: ^6.0.0
  date_picker_plus: ^3.0.2
  fl_chart: ^0.68.0
  file_picker: ^8.0.0
  get_storage: ^2.1.1
  supabase_flutter: ^2.5.2
  powersync: ^1.3.1
  path: ^1.8.3
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  window_manager: ^0.3.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/google.svg
    - .env
