// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDg2bs6T8npgh2RkFGDxU4xf3-Ts6wxSkU',
//     appId: '1:969054215392:web:b6f73d3d7c50dc79cbc485',
//     messagingSenderId: '969054215392',
//     projectId: 'materi-kas',
//     authDomain: 'materi-kas.firebaseapp.com',
//     databaseURL: 'https://materi-kas-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'materi-kas.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAxVEl2fJK_yLYIBQM7e3onHY5rRPkiUfY',
//     appId: '1:969054215392:android:723d71b5cec680dbcbc485',
//     messagingSenderId: '969054215392',
//     projectId: 'materi-kas',
//     databaseURL: 'https://materi-kas-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'materi-kas.appspot.com',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDg2bs6T8npgh2RkFGDxU4xf3-Ts6wxSkU',
//     appId: '1:969054215392:web:b6f73d3d7c50dc79cbc485',
//     messagingSenderId: '969054215392',
//     projectId: 'materi-kas',
//     authDomain: 'materi-kas.firebaseapp.com',
//     databaseURL: 'https://materi-kas-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'materi-kas.appspot.com',
//   );

// }