// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNCilrbDyF1eSdqpRZMXWAO6_ibXGO1I',
    appId: '1:13933506648:web:c7e8370f75ba156a989a2d',
    messagingSenderId: '13933506648',
    projectId: 'materikas-e152b',
    authDomain: 'materikas-e152b.firebaseapp.com',
    storageBucket: 'materikas-e152b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GOBES33ubL1fAlrcPJQfaTco1ADnzKA',
    appId: '1:13933506648:android:3f5093015d379787989a2d',
    messagingSenderId: '13933506648',
    projectId: 'materikas-e152b',
    storageBucket: 'materikas-e152b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuNCilrbDyF1eSdqpRZMXWAO6_ibXGO1I',
    appId: '1:13933506648:web:cacc4669b1ba5d3d989a2d',
    messagingSenderId: '13933506648',
    projectId: 'materikas-e152b',
    authDomain: 'materikas-e152b.firebaseapp.com',
    storageBucket: 'materikas-e152b.appspot.com',
  );
}
